/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VieEtudianteRouteImport } from './routes/vie-etudiante'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin._authenticated.index'
import { Route as AdminAuthenticatedEtudiantsRouteImport } from './routes/admin._authenticated.etudiants'
import { Route as AdminAuthenticatedCandidaturesRouteImport } from './routes/admin._authenticated.candidatures'
import { Route as AdminAuthenticatedCandidaturesIdRouteImport } from './routes/admin._authenticated.candidatures.$id'

const VieEtudianteRoute = VieEtudianteRouteImport.update({
  id: '/vie-etudiante',
  path: '/vie-etudiante',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedEtudiantsRoute =
  AdminAuthenticatedEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCandidaturesRoute =
  AdminAuthenticatedCandidaturesRouteImport.update({
    id: '/candidatures',
    path: '/candidatures',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCandidaturesIdRoute =
  AdminAuthenticatedCandidaturesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAuthenticatedCandidaturesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/inscription': typeof InscriptionRoute
  '/international': typeof InternationalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/programmes': typeof ProgrammesRoute
  '/verification': typeof VerificationRoute
  '/vie-etudiante': typeof VieEtudianteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/candidatures': typeof AdminAuthenticatedCandidaturesRouteWithChildren
  '/admin/etudiants': typeof AdminAuthenticatedEtudiantsRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/candidatures/$id': typeof AdminAuthenticatedCandidaturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admissions': typeof AdmissionsRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/inscription': typeof InscriptionRoute
  '/international': typeof InternationalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/programmes': typeof ProgrammesRoute
  '/verification': typeof VerificationRoute
  '/vie-etudiante': typeof VieEtudianteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/candidatures': typeof AdminAuthenticatedCandidaturesRouteWithChildren
  '/admin/etudiants': typeof AdminAuthenticatedEtudiantsRoute
  '/admin/candidatures/$id': typeof AdminAuthenticatedCandidaturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/inscription': typeof InscriptionRoute
  '/international': typeof InternationalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/programmes': typeof ProgrammesRoute
  '/verification': typeof VerificationRoute
  '/vie-etudiante': typeof VieEtudianteRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authenticated/candidatures': typeof AdminAuthenticatedCandidaturesRouteWithChildren
  '/admin/_authenticated/etudiants': typeof AdminAuthenticatedEtudiantsRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/candidatures/$id': typeof AdminAuthenticatedCandidaturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admissions'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/inscription'
    | '/international'
    | '/mentions-legales'
    | '/programmes'
    | '/verification'
    | '/vie-etudiante'
    | '/admin/login'
    | '/admin/candidatures'
    | '/admin/etudiants'
    | '/admin/'
    | '/admin/candidatures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admissions'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/inscription'
    | '/international'
    | '/mentions-legales'
    | '/programmes'
    | '/verification'
    | '/vie-etudiante'
    | '/admin/login'
    | '/admin/candidatures'
    | '/admin/etudiants'
    | '/admin/candidatures/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admissions'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/inscription'
    | '/international'
    | '/mentions-legales'
    | '/programmes'
    | '/verification'
    | '/vie-etudiante'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/admin/_authenticated/candidatures'
    | '/admin/_authenticated/etudiants'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/candidatures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  InscriptionRoute: typeof InscriptionRoute
  InternationalRoute: typeof InternationalRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ProgrammesRoute: typeof ProgrammesRoute
  VerificationRoute: typeof VerificationRoute
  VieEtudianteRoute: typeof VieEtudianteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vie-etudiante': {
      id: '/vie-etudiante'
      path: '/vie-etudiante'
      fullPath: '/vie-etudiante'
      preLoaderRoute: typeof VieEtudianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/etudiants': {
      id: '/admin/_authenticated/etudiants'
      path: '/etudiants'
      fullPath: '/admin/etudiants'
      preLoaderRoute: typeof AdminAuthenticatedEtudiantsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/candidatures': {
      id: '/admin/_authenticated/candidatures'
      path: '/candidatures'
      fullPath: '/admin/candidatures'
      preLoaderRoute: typeof AdminAuthenticatedCandidaturesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/candidatures/$id': {
      id: '/admin/_authenticated/candidatures/$id'
      path: '/$id'
      fullPath: '/admin/candidatures/$id'
      preLoaderRoute: typeof AdminAuthenticatedCandidaturesIdRouteImport
      parentRoute: typeof AdminAuthenticatedCandidaturesRoute
    }
  }
}

interface AdminAuthenticatedCandidaturesRouteChildren {
  AdminAuthenticatedCandidaturesIdRoute: typeof AdminAuthenticatedCandidaturesIdRoute
}

const AdminAuthenticatedCandidaturesRouteChildren: AdminAuthenticatedCandidaturesRouteChildren =
  {
    AdminAuthenticatedCandidaturesIdRoute:
      AdminAuthenticatedCandidaturesIdRoute,
  }

const AdminAuthenticatedCandidaturesRouteWithChildren =
  AdminAuthenticatedCandidaturesRoute._addFileChildren(
    AdminAuthenticatedCandidaturesRouteChildren,
  )

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedCandidaturesRoute: typeof AdminAuthenticatedCandidaturesRouteWithChildren
  AdminAuthenticatedEtudiantsRoute: typeof AdminAuthenticatedEtudiantsRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedCandidaturesRoute:
    AdminAuthenticatedCandidaturesRouteWithChildren,
  AdminAuthenticatedEtudiantsRoute: AdminAuthenticatedEtudiantsRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  InscriptionRoute: InscriptionRoute,
  InternationalRoute: InternationalRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ProgrammesRoute: ProgrammesRoute,
  VerificationRoute: VerificationRoute,
  VieEtudianteRoute: VieEtudianteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
