/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialisationsRouteImport } from './routes/specialisations'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as IndexRouteImport } from './routes/index'

const SpecialisationsRoute = SpecialisationsRouteImport.update({
  id: '/specialisations',
  path: '/specialisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/international': typeof InternationalRoute
  '/programmes': typeof ProgrammesRoute
  '/specialisations': typeof SpecialisationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/international': typeof InternationalRoute
  '/programmes': typeof ProgrammesRoute
  '/specialisations': typeof SpecialisationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/international': typeof InternationalRoute
  '/programmes': typeof ProgrammesRoute
  '/specialisations': typeof SpecialisationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/contact'
    | '/international'
    | '/programmes'
    | '/specialisations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/contact'
    | '/international'
    | '/programmes'
    | '/specialisations'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/contact'
    | '/international'
    | '/programmes'
    | '/specialisations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  InternationalRoute: typeof InternationalRoute
  ProgrammesRoute: typeof ProgrammesRoute
  SpecialisationsRoute: typeof SpecialisationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialisations': {
      id: '/specialisations'
      path: '/specialisations'
      fullPath: '/specialisations'
      preLoaderRoute: typeof SpecialisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  InternationalRoute: InternationalRoute,
  ProgrammesRoute: ProgrammesRoute,
  SpecialisationsRoute: SpecialisationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
