/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as IndexRouteImport } from './routes/index'

const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/international': typeof InternationalRoute
  '/programmes': typeof ProgrammesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/international': typeof InternationalRoute
  '/programmes': typeof ProgrammesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/international': typeof InternationalRoute
  '/programmes': typeof ProgrammesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admissions' | '/contact' | '/international' | '/programmes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admissions' | '/contact' | '/international' | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/contact'
    | '/international'
    | '/programmes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  InternationalRoute: typeof InternationalRoute
  ProgrammesRoute: typeof ProgrammesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  InternationalRoute: InternationalRoute,
  ProgrammesRoute: ProgrammesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
